/**
 * Server-side content mirror.
 *
 * Two things the backend must not take from the client are seeded here from the
 * bundled question bank:
 *
 *   `public.lesson_catalog`   — how many questions each lesson has and what it
 *                               pays, so `complete_lesson` cannot be told to
 *                               mint XP;
 *   `public.question_rubrics` — the snippet and key points every AI-graded
 *                               question is marked against.
 *
 * Run it whenever the question bank changes:
 *
 *   npm run content:seed && npm run supabase:push
 *
 * @module scripts/generate_content_seed
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { lessonXp, unitSchema, type Unit } from '../lib/content_schema.ts';

const ROOT = resolve(import.meta.dirname, '..');
const CONTENT_DIR = join(ROOT, 'content');
const COURSES = ['python', 'javascript'] as const;
const OUTPUT = join(ROOT, 'supabase', 'migrations', '20260818130000_seed_content_mirror.sql');

/** Postgres string literal, dollar-quoted so code snippets need no escaping. */
function literal(value: string): string {
  let tag = 'q';
  while (value.includes(`$${tag}$`)) tag += 'q';
  return `$${tag}$${value}$${tag}$`;
}

function loadUnits(): Unit[] {
  const units: Unit[] = [];
  for (const course of COURSES) {
    const dir = join(CONTENT_DIR, course);
    let entries: string[] = [];
    try {
      entries = readdirSync(dir);
    } catch {
      continue;
    }
    for (const entry of entries.sort()) {
      if (!/^unit_\d{2}\.json$/.test(entry)) continue;
      const parsed = unitSchema.safeParse(JSON.parse(readFileSync(join(dir, entry), 'utf8')));
      if (!parsed.success) {
        console.error(`${course}/${entry} does not match the schema — run npm run content:check`);
        process.exit(1);
      }
      units.push(parsed.data);
    }
  }
  return units;
}

function main(): void {
  const units = loadUnits();
  const rows: string[] = [];
  const catalog: string[] = [];

  for (const unit of units) {
    for (const lesson of unit.lessons) {
      catalog.push(
        [
          '  (',
          `    ${literal(lesson.id)},`,
          `    ${literal(unit.id)},`,
          `    ${literal(unit.courseId)},`,
          `    ${lesson.questions.length},`,
          `    ${lessonXp(lesson)}`,
          '  )',
        ].join('\n')
      );
    }
  }

  for (const unit of units) {
    for (const lesson of unit.lessons) {
      for (const question of lesson.questions) {
        if (question.type !== 'explain_code') continue;
        rows.push(
          [
            '  (',
            `    ${literal(question.id)},`,
            `    ${literal(unit.courseId)},`,
            `    ${literal(lesson.id)},`,
            `    ${literal(question.code.en)},`,
            `    ${literal(question.code.tr)},`,
            `    ${literal(JSON.stringify(question.keyPoints.en))}::jsonb,`,
            `    ${literal(JSON.stringify(question.keyPoints.tr))}::jsonb`,
            '  )',
          ].join('\n')
        );
      }
    }
  }

  if (rows.length === 0) {
    console.error('No explain_code questions found — refusing to write an empty seed.');
    process.exit(1);
  }

  const sql = [
    '-- Generated by `npm run content:seed`. Do not edit by hand.',
    '--',
    '-- Mirrors what the backend must not take from the client: what each lesson',
    '-- is worth, and the grading rubric of every explain_code question.',
    '',
    'insert into public.lesson_catalog',
    '  (lesson_id, unit_id, course_id, question_count, base_xp)',
    'values',
    `${catalog.join(',\n')}`,
    'on conflict (lesson_id) do update set',
    '  unit_id = excluded.unit_id,',
    '  course_id = excluded.course_id,',
    '  question_count = excluded.question_count,',
    '  base_xp = excluded.base_xp,',
    '  updated_at = now();',
    '',
    'delete from public.lesson_catalog',
    'where lesson_id not in (',
    units.flatMap((unit) => unit.lessons.map((lesson) => `  ${literal(lesson.id)}`)).join(',\n'),
    ');',
    '',
    'insert into public.question_rubrics',
    '  (question_id, course_id, lesson_id, code_en, code_tr, key_points_en, key_points_tr)',
    'values',
    `${rows.join(',\n')}`,
    'on conflict (question_id) do update set',
    '  course_id = excluded.course_id,',
    '  lesson_id = excluded.lesson_id,',
    '  code_en = excluded.code_en,',
    '  code_tr = excluded.code_tr,',
    '  key_points_en = excluded.key_points_en,',
    '  key_points_tr = excluded.key_points_tr,',
    '  updated_at = now();',
    '',
    '-- Rubrics for questions that no longer exist in the bundle are dropped so a',
    '-- stale id cannot be graded.',
    'delete from public.question_rubrics',
    'where question_id not in (',
    units
      .flatMap((unit) =>
        unit.lessons.flatMap((lesson) =>
          lesson.questions
            .filter((question) => question.type === 'explain_code')
            .map((question) => `  ${literal(question.id)}`)
        )
      )
      .join(',\n'),
    ');',
    '',
  ].join('\n');

  writeFileSync(OUTPUT, sql);
  console.log(
    `Wrote ${catalog.length} catalog rows and ${rows.length} rubric rows to ` +
      OUTPUT.replace(`${ROOT}/`, '')
  );
}

main();
