-- Generated by `npm run content:seed`. Do not edit by hand.
--
-- Mirrors what the backend must not take from the client: what each lesson
-- is worth, and the grading rubric of every explain_code question.

insert into public.lesson_catalog
  (lesson_id, unit_id, course_id, question_count, base_xp)
values
  (
    $q$py-u01-l1$q$,
    $q$py-u01$q$,
    $q$python$q$,
    6,
    70
  ),
  (
    $q$py-u01-l2$q$,
    $q$py-u01$q$,
    $q$python$q$,
    6,
    75
  ),
  (
    $q$py-u01-l3$q$,
    $q$py-u01$q$,
    $q$python$q$,
    6,
    105
  ),
  (
    $q$py-u01-l4$q$,
    $q$py-u01$q$,
    $q$python$q$,
    6,
    120
  ),
  (
    $q$py-u02-l1$q$,
    $q$py-u02$q$,
    $q$python$q$,
    6,
    75
  ),
  (
    $q$py-u02-l2$q$,
    $q$py-u02$q$,
    $q$python$q$,
    6,
    80
  ),
  (
    $q$py-u02-l3$q$,
    $q$py-u02$q$,
    $q$python$q$,
    6,
    95
  ),
  (
    $q$py-u02-l4$q$,
    $q$py-u02$q$,
    $q$python$q$,
    6,
    100
  ),
  (
    $q$py-u03-l1$q$,
    $q$py-u03$q$,
    $q$python$q$,
    6,
    75
  ),
  (
    $q$py-u03-l2$q$,
    $q$py-u03$q$,
    $q$python$q$,
    6,
    80
  ),
  (
    $q$py-u03-l3$q$,
    $q$py-u03$q$,
    $q$python$q$,
    6,
    95
  ),
  (
    $q$py-u03-l4$q$,
    $q$py-u03$q$,
    $q$python$q$,
    6,
    105
  ),
  (
    $q$py-u04-l1$q$,
    $q$py-u04$q$,
    $q$python$q$,
    6,
    70
  ),
  (
    $q$py-u04-l2$q$,
    $q$py-u04$q$,
    $q$python$q$,
    6,
    75
  ),
  (
    $q$py-u04-l3$q$,
    $q$py-u04$q$,
    $q$python$q$,
    6,
    95
  ),
  (
    $q$py-u04-l4$q$,
    $q$py-u04$q$,
    $q$python$q$,
    6,
    105
  ),
  (
    $q$py-u05-l1$q$,
    $q$py-u05$q$,
    $q$python$q$,
    6,
    75
  ),
  (
    $q$py-u05-l2$q$,
    $q$py-u05$q$,
    $q$python$q$,
    6,
    75
  ),
  (
    $q$py-u05-l3$q$,
    $q$py-u05$q$,
    $q$python$q$,
    6,
    85
  ),
  (
    $q$py-u05-l4$q$,
    $q$py-u05$q$,
    $q$python$q$,
    6,
    120
  ),
  (
    $q$py-u06-l1$q$,
    $q$py-u06$q$,
    $q$python$q$,
    6,
    75
  ),
  (
    $q$py-u06-l2$q$,
    $q$py-u06$q$,
    $q$python$q$,
    6,
    75
  ),
  (
    $q$py-u06-l3$q$,
    $q$py-u06$q$,
    $q$python$q$,
    6,
    85
  ),
  (
    $q$py-u06-l4$q$,
    $q$py-u06$q$,
    $q$python$q$,
    6,
    120
  ),
  (
    $q$py-u07-l1$q$,
    $q$py-u07$q$,
    $q$python$q$,
    6,
    75
  ),
  (
    $q$py-u07-l2$q$,
    $q$py-u07$q$,
    $q$python$q$,
    6,
    95
  ),
  (
    $q$py-u07-l3$q$,
    $q$py-u07$q$,
    $q$python$q$,
    6,
    100
  ),
  (
    $q$py-u07-l4$q$,
    $q$py-u07$q$,
    $q$python$q$,
    6,
    110
  ),
  (
    $q$py-u08-l1$q$,
    $q$py-u08$q$,
    $q$python$q$,
    6,
    75
  ),
  (
    $q$py-u08-l2$q$,
    $q$py-u08$q$,
    $q$python$q$,
    6,
    95
  ),
  (
    $q$py-u08-l3$q$,
    $q$py-u08$q$,
    $q$python$q$,
    6,
    95
  ),
  (
    $q$py-u08-l4$q$,
    $q$py-u08$q$,
    $q$python$q$,
    6,
    130
  ),
  (
    $q$js-u01-l1$q$,
    $q$js-u01$q$,
    $q$javascript$q$,
    6,
    70
  ),
  (
    $q$js-u01-l2$q$,
    $q$js-u01$q$,
    $q$javascript$q$,
    6,
    75
  ),
  (
    $q$js-u01-l3$q$,
    $q$js-u01$q$,
    $q$javascript$q$,
    6,
    95
  ),
  (
    $q$js-u01-l4$q$,
    $q$js-u01$q$,
    $q$javascript$q$,
    6,
    115
  ),
  (
    $q$js-u02-l1$q$,
    $q$js-u02$q$,
    $q$javascript$q$,
    6,
    70
  ),
  (
    $q$js-u02-l2$q$,
    $q$js-u02$q$,
    $q$javascript$q$,
    6,
    75
  ),
  (
    $q$js-u02-l3$q$,
    $q$js-u02$q$,
    $q$javascript$q$,
    6,
    85
  ),
  (
    $q$js-u02-l4$q$,
    $q$js-u02$q$,
    $q$javascript$q$,
    6,
    95
  ),
  (
    $q$js-u03-l1$q$,
    $q$js-u03$q$,
    $q$javascript$q$,
    6,
    70
  ),
  (
    $q$js-u03-l2$q$,
    $q$js-u03$q$,
    $q$javascript$q$,
    6,
    80
  ),
  (
    $q$js-u03-l3$q$,
    $q$js-u03$q$,
    $q$javascript$q$,
    6,
    105
  ),
  (
    $q$js-u03-l4$q$,
    $q$js-u03$q$,
    $q$javascript$q$,
    6,
    120
  ),
  (
    $q$js-u04-l1$q$,
    $q$js-u04$q$,
    $q$javascript$q$,
    6,
    75
  ),
  (
    $q$js-u04-l2$q$,
    $q$js-u04$q$,
    $q$javascript$q$,
    6,
    80
  ),
  (
    $q$js-u04-l3$q$,
    $q$js-u04$q$,
    $q$javascript$q$,
    6,
    120
  ),
  (
    $q$js-u04-l4$q$,
    $q$js-u04$q$,
    $q$javascript$q$,
    6,
    120
  ),
  (
    $q$js-u05-l1$q$,
    $q$js-u05$q$,
    $q$javascript$q$,
    6,
    75
  ),
  (
    $q$js-u05-l2$q$,
    $q$js-u05$q$,
    $q$javascript$q$,
    6,
    75
  ),
  (
    $q$js-u05-l3$q$,
    $q$js-u05$q$,
    $q$javascript$q$,
    6,
    95
  ),
  (
    $q$js-u05-l4$q$,
    $q$js-u05$q$,
    $q$javascript$q$,
    6,
    110
  ),
  (
    $q$js-u06-l1$q$,
    $q$js-u06$q$,
    $q$javascript$q$,
    6,
    70
  ),
  (
    $q$js-u06-l2$q$,
    $q$js-u06$q$,
    $q$javascript$q$,
    6,
    90
  ),
  (
    $q$js-u06-l3$q$,
    $q$js-u06$q$,
    $q$javascript$q$,
    6,
    90
  ),
  (
    $q$js-u06-l4$q$,
    $q$js-u06$q$,
    $q$javascript$q$,
    6,
    120
  )
on conflict (lesson_id) do update set
  unit_id = excluded.unit_id,
  course_id = excluded.course_id,
  question_count = excluded.question_count,
  base_xp = excluded.base_xp,
  updated_at = now();

delete from public.lesson_catalog
where lesson_id not in (
  $q$py-u01-l1$q$,
  $q$py-u01-l2$q$,
  $q$py-u01-l3$q$,
  $q$py-u01-l4$q$,
  $q$py-u02-l1$q$,
  $q$py-u02-l2$q$,
  $q$py-u02-l3$q$,
  $q$py-u02-l4$q$,
  $q$py-u03-l1$q$,
  $q$py-u03-l2$q$,
  $q$py-u03-l3$q$,
  $q$py-u03-l4$q$,
  $q$py-u04-l1$q$,
  $q$py-u04-l2$q$,
  $q$py-u04-l3$q$,
  $q$py-u04-l4$q$,
  $q$py-u05-l1$q$,
  $q$py-u05-l2$q$,
  $q$py-u05-l3$q$,
  $q$py-u05-l4$q$,
  $q$py-u06-l1$q$,
  $q$py-u06-l2$q$,
  $q$py-u06-l3$q$,
  $q$py-u06-l4$q$,
  $q$py-u07-l1$q$,
  $q$py-u07-l2$q$,
  $q$py-u07-l3$q$,
  $q$py-u07-l4$q$,
  $q$py-u08-l1$q$,
  $q$py-u08-l2$q$,
  $q$py-u08-l3$q$,
  $q$py-u08-l4$q$,
  $q$js-u01-l1$q$,
  $q$js-u01-l2$q$,
  $q$js-u01-l3$q$,
  $q$js-u01-l4$q$,
  $q$js-u02-l1$q$,
  $q$js-u02-l2$q$,
  $q$js-u02-l3$q$,
  $q$js-u02-l4$q$,
  $q$js-u03-l1$q$,
  $q$js-u03-l2$q$,
  $q$js-u03-l3$q$,
  $q$js-u03-l4$q$,
  $q$js-u04-l1$q$,
  $q$js-u04-l2$q$,
  $q$js-u04-l3$q$,
  $q$js-u04-l4$q$,
  $q$js-u05-l1$q$,
  $q$js-u05-l2$q$,
  $q$js-u05-l3$q$,
  $q$js-u05-l4$q$,
  $q$js-u06-l1$q$,
  $q$js-u06-l2$q$,
  $q$js-u06-l3$q$,
  $q$js-u06-l4$q$
);

insert into public.question_rubrics
  (question_id, course_id, lesson_id, code_en, code_tr, key_points_en, key_points_tr)
values
  (
    $q$py-u01-l1-q6$q$,
    $q$python$q$,
    $q$py-u01-l1$q$,
    $q$# This shows two numbers
print(6)
print(9)$q$,
    $q$# Bu iki sayıyı gösterir
print(6)
print(9)$q$,
    $q$["the first print outputs 6","the second print outputs 9","each print creates a new line"]$q$::jsonb,
    $q$["ilk print 6'yı çıktı verir","ikinci print 9'u çıktı verir","her print yeni bir satır oluşturur"]$q$::jsonb
  ),
  (
    $q$py-u01-l2-q6$q$,
    $q$python$q$,
    $q$py-u01-l2$q$,
    $q$# Announce the winner
print("Winner:", "Alice", "Score:", 98)$q$,
    $q$# Kazananı duyur
print("Winner:", "Alice", "Score:", 98)$q$,
    $q$["uses a comment to explain the code's purpose","prints four separate values using commas","Python joins them with spaces on one line"]$q$::jsonb,
    $q$["kodun amacını açıklamak için bir yorum kullanır","virgülleri kullanarak dört ayrı değeri yazdırır","Python onları tek satırda boşluklarla birleştirir"]$q$::jsonb
  ),
  (
    $q$py-u01-l3-q6$q$,
    $q$python$q$,
    $q$py-u01-l3$q$,
    $q$# Store a book title
title = "Python Basics"
print("Reading:", title)$q$,
    $q$# Bir kitap başlığını sakla
title = "Python Basics"
print("Reading:", title)$q$,
    $q$["creates a variable called title","stores the text Python Basics in that variable","prints Reading followed by the value of the title variable"]$q$::jsonb,
    $q$["title adlı bir değişken oluşturur","Python Basics metnini bu değişkende saklar","Reading'i takip eden title değişkeninin değerini yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u01-l4-q6$q$,
    $q$python$q$,
    $q$py-u01-l4$q$,
    $q$# Show a greeting
name = "Jordan"
greeting = "Hi"
print(greeting, "to", name)$q$,
    $q$# Bir selamlamayı göster
name = "Jordan"
greeting = "Hi"
print(greeting, "to", name)$q$,
    $q$["creates variables in order: name then greeting","each variable stores a text value","prints all three values separated by commas"]$q$::jsonb,
    $q$["sırayla değişkenler oluşturur: name sonra greeting","her değişken bir metin değerini depolar","virgüllerle ayrılmış üç değeri yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u02-l1-q6$q$,
    $q$python$q$,
    $q$py-u02-l1$q$,
    $q$# Store and display information
first_name = "Sarah"
last_name = "Chen"
print(first_name)
print(last_name)$q$,
    $q$# Bilgiyi sakla ve göster
first_name = "Sarah"
last_name = "Chen"
print(first_name)
print(last_name)$q$,
    $q$["creates a variable first_name and stores the text Sarah","creates a variable last_name and stores the text Chen","prints each variable on its own line"]$q$::jsonb,
    $q$["first_name değişkenini oluşturur ve Sarah metnini saklar","last_name değişkenini oluşturur ve Chen metnini saklar","her değişkeni kendi satırında yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u02-l2-q6$q$,
    $q$python$q$,
    $q$py-u02-l2$q$,
    $q$# Store three different types
age = 30
height = 5.9
city = "Berlin"
print(age)
print(height)
print(city)$q$,
    $q$# Üç farklı türü sakla
age = 30
height = 5.9
city = "Berlin"
print(age)
print(height)
print(city)$q$,
    $q$["stores the whole number 30 in age (int type)","stores the decimal number 5.9 in height (float type)","stores the text Berlin in city (str type)","prints each variable"]$q$::jsonb,
    $q$["tam sayı 30'u age'de saklar (int türü)","ondalık sayı 5.9'u height'ta saklar (float türü)","metin Berlin'i city'de saklar (str türü)","her değişkeni yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u02-l3-q6$q$,
    $q$python$q$,
    $q$py-u02-l3$q$,
    $q$# Convert and check types
original = "99"
converted = int(original)
print(type(original))
print(type(converted))$q$,
    $q$# Dönüştür ve türleri kontrol et
original = "99"
converted = int(original)
print(type(original))
print(type(converted))$q$,
    $q$["stores the string \"99\" in original","converts it to the int 99 and stores in converted","type(original) shows the first is a str","type(converted) shows the second is an int"]$q$::jsonb,
    $q$["string \"99\"'u original'da saklar","onu int 99'a dönüştürür ve converted'e saklar","type(original) birincinin str olduğunu gösterir","type(converted) ikincinin int olduğunu gösterir"]$q$::jsonb
  ),
  (
    $q$py-u02-l4-q6$q$,
    $q$python$q$,
    $q$py-u02-l4$q$,
    $q$# Track status with booleans and absence with None
is_active = True
is_admin = False
last_login = None
print(type(is_active))
print(type(is_admin))
print(type(last_login))$q$,
    $q$# Boolean'larla durumu ve None ile yokluğu takip et
is_active = True
is_admin = False
last_login = None
print(type(is_active))
print(type(is_admin))
print(type(last_login))$q$,
    $q$["stores True in is_active (boolean type)","stores False in is_admin (boolean type)","stores None in last_login (NoneType)","prints the type of each variable"]$q$::jsonb,
    $q$["True'yu is_active'e saklar (boolean türü)","False'u is_admin'e saklar (boolean türü)","None'ı last_login'e saklar (NoneType)","her değişkenin türünü yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u03-l1-q6$q$,
    $q$python$q$,
    $q$py-u03-l1$q$,
    $q$# Builds a decorative line
line = "*" * 10 + "-" * 3 + "*" * 10
print(line)$q$,
    $q$# Dekoratif bir satır oluşturur
line = "*" * 10 + "-" * 3 + "*" * 10
print(line)$q$,
    $q$["repeats the asterisk 10 times","repeats the hyphen 3 times","joins them together with +","prints the combined pattern"]$q$::jsonb,
    $q$["yıldızı 10 kez tekrarlar","tireyi 3 kez tekrarlar","onları + ile birleştirir","birleşen deseni yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u03-l2-q6$q$,
    $q$python$q$,
    $q$py-u03-l2$q$,
    $q$# Displays the first and last character of a word
word = "hello"
print(word[0])
print(word[-1])$q$,
    $q$# Bir kelimenin ilk ve son karakterini gösterir
word = "hello"
print(word[0])
print(word[-1])$q$,
    $q$["stores hello in word","accesses the first character with [0]","accesses the last character with [-1]","prints each one on a separate line"]$q$::jsonb,
    $q$["hello'yu word'e saklar","[0] ile ilk karaktere erişir","[-1] ile son karaktere erişir","her birini ayrı satırda yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u03-l3-q6$q$,
    $q$python$q$,
    $q$py-u03-l3$q$,
    $q$# Splits a date into year, month, and day
date = "2024-08-18"
year = date[0:4]
month = date[5:7]
day = date[8:10]
print(year, month, day)$q$,
    $q$# Bir tarihi yıl, ay ve güne ayırır
date = "2024-08-18"
year = date[0:4]
month = date[5:7]
day = date[8:10]
print(year, month, day)$q$,
    $q$["slices the year from date[0:4]","slices the month from date[5:7]","slices the day from date[8:10]","prints all three values together"]$q$::jsonb,
    $q$["date[0:4] ile yılı dilimler","date[5:7] ile ayı dilimler","date[8:10] ile günü dilimler","üç değeri birlikte yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u03-l4-q6$q$,
    $q$python$q$,
    $q$py-u03-l4$q$,
    $q$# Creates a username from a full name
full_name = "  Alice Johnson  "
clean = full_name.strip().lower()
username = clean.replace(" ", "_")
print(f"Username: {username}")$q$,
    $q$# Tam bir addan kullanıcı adı oluşturur
full_name = "  Alice Johnson  "
clean = full_name.strip().lower()
username = clean.replace(" ", "_")
print(f"Username: {username}")$q$,
    $q$["removes leading and trailing spaces with strip()","converts to lowercase with lower()","replaces spaces with underscores using replace()","uses an f-string to display the final username"]$q$::jsonb,
    $q$["strip() ile başındaki ve sonundaki boşlukları kaldırır","lower() ile küçük harfe çevirir","replace() ile boşlukları alt çizgilerle değiştirir","son kullanıcı adını göstermek için f-string kullanır"]$q$::jsonb
  ),
  (
    $q$py-u04-l1-q6$q$,
    $q$python$q$,
    $q$py-u04-l1$q$,
    $q$# Calculate the cost of three items
price = 12
quantity = 3
total = price * quantity
print(total)$q$,
    $q$# Üç öğenin maliyetini hesapla
price = 12
quantity = 3
total = price * quantity
print(total)$q$,
    $q$["stores the price 12 in a variable","stores the quantity 3 in another variable","multiplies price by quantity","prints the total result"]$q$::jsonb,
    $q$["fiyat 12'yi bir değişkende saklar","miktarı 3'ü başka bir değişkende saklar","fiyat ile miktarı çarpar","toplam sonucu yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u04-l2-q6$q$,
    $q$python$q$,
    $q$py-u04-l2$q$,
    $q$# Check if the number is even
number = 8
print(number % 2)$q$,
    $q$# Sayının çift olup olmadığını kontrol et
number = 8
print(number % 2)$q$,
    $q$["stores the number 8","calculates the remainder of number divided by 2","prints 0, since 8 divides evenly with no remainder"]$q$::jsonb,
    $q$["sayıyı 8 olarak saklar","number'ın 2'ye bölümünden kalanı hesaplar","kalan 0 olduğu için 0 yazdırır, bu da 8'in çift olduğunu gösterir"]$q$::jsonb
  ),
  (
    $q$py-u04-l3-q6$q$,
    $q$python$q$,
    $q$py-u04-l3$q$,
    $q$# Calculate the area of a square
side = 5
area = side ** 2
print(area)$q$,
    $q$# Karenin alanını hesapla
side = 5
area = side ** 2
print(area)$q$,
    $q$["stores the side length 5","raises that side length to the power of 2 (multiplies it by itself)","saves the result in area","prints the area"]$q$::jsonb,
    $q$["kenar uzunluğu 5'i saklar","o kenar uzunluğunu 2 üssüne yükseltir (kendisiyle çarpar)","sonucu area'da saklar","alanı yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u04-l4-q6$q$,
    $q$python$q$,
    $q$py-u04-l4$q$,
    $q$# Check if the temperature is below freezing
temp = -3
print(temp < 0)$q$,
    $q$# Sıcaklığın donma noktasının altında olup olmadığını kontrol et
temp = -3
print(temp < 0)$q$,
    $q$["stores the temperature -3","compares it to 0 using the < operator","prints True because -3 is less than 0"]$q$::jsonb,
    $q$["sıcaklığı -3 olarak saklar","onu 0 ile < kullanarak karşılaştırır","True yazdırır çünkü -3 0'dan küçüktür"]$q$::jsonb
  ),
  (
    $q$py-u05-l1-q6$q$,
    $q$python$q$,
    $q$py-u05-l1$q$,
    $q$# Decide what to do based on the time of day
hour = 14
if hour < 12:
    print("Good morning")
else:
    print("Good afternoon")$q$,
    $q$# Günün saatine bağlı olarak ne yapacağına karar ver
hour = 14
if hour < 12:
    print("Good morning")
else:
    print("Good afternoon")$q$,
    $q$["stores the hour as 14","tests if it is before noon","prints the appropriate greeting"]$q$::jsonb,
    $q$["saati 14 olarak saklar","öğlen öncesi olup olmadığını test eder","uygun selamlamayı yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u05-l2-q6$q$,
    $q$python$q$,
    $q$py-u05-l2$q$,
    $q$# Assign a ticket price based on age
age = 15
if age < 5:
    print("Free")
elif age < 13:
    print("Child")
elif age < 18:
    print("Teen")
else:
    print("Adult")$q$,
    $q$# Yaşa bağlı olarak bilet fiyatı ata
age = 15
if age < 5:
    print("Free")
elif age < 13:
    print("Child")
elif age < 18:
    print("Teen")
else:
    print("Adult")$q$,
    $q$["stores age as 15","tests age categories with elif in order","prints the matching category"]$q$::jsonb,
    $q$["yaşı 15 olarak saklar","elif ile sırasıyla yaş kategorilerini test eder","eşleşen kategoriyi yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u05-l3-q6$q$,
    $q$python$q$,
    $q$py-u05-l3$q$,
    $q$# Check if the user has permission and is signed in
logged_in = True
admin = False
if logged_in and admin:
    print("Full access")
elif logged_in:
    print("Basic access")
else:
    print("No access")$q$,
    $q$# Kullanıcının izninin olup olmadığını ve oturum açıp açmadığını kontrol et
logged_in = True
admin = False
if logged_in and admin:
    print("Full access")
elif logged_in:
    print("Basic access")
else:
    print("No access")$q$,
    $q$["stores login and permission status","requires both logged_in and admin for full access","grants basic access to logged-in users"]$q$::jsonb,
    $q$["giriş ve izin durumunu saklar","tam erişim için hem logged_in hem de admin'i ister","giriş yapmış kullanıcılara temel erişim verir"]$q$::jsonb
  ),
  (
    $q$py-u05-l4-q6$q$,
    $q$python$q$,
    $q$py-u05-l4$q$,
    $q$# Check age-based access in stages
age = 14
if age >= 13:
    if age >= 18:
        print("Can vote")
    else:
        print("Can use, no vote")
else:
    print("Too young")$q$,
    $q$# Yaşa dayalı erişimi aşamalar halinde kontrol et
age = 14
if age >= 13:
    if age >= 18:
        print("Can vote")
    else:
        print("Can use, no vote")
else:
    print("Too young")$q$,
    $q$["stores age as 14","first checks if at least 13","then checks if at least 18 for voting","provides different access levels"]$q$::jsonb,
    $q$["yaşı 14 olarak saklar","önce en az 13 olup olmadığını kontrol eder","sonra oy vermek için en az 18 olup olmadığını kontrol eder","farklı erişim seviyeleri sağlar"]$q$::jsonb
  ),
  (
    $q$py-u06-l1-q6$q$,
    $q$python$q$,
    $q$py-u06-l1$q$,
    $q$# Count up from zero
for num in range(5):
    print(num)$q$,
    $q$# Sıfırdan saymaya başla
for num in range(5):
    print(num)$q$,
    $q$["uses a for loop to repeat five times","range(5) produces 0, 1, 2, 3, 4","prints each number on its own line"]$q$::jsonb,
    $q$["for döngüsü ile beş kez tekrarlar","range(5) sıfır, bir, iki, üç, dördü üretir","her sayıyı kendi satırında yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u06-l2-q6$q$,
    $q$python$q$,
    $q$py-u06-l2$q$,
    $q$# Check each number
nums = [2, 4, 6]
for n in nums:
    print(n * 2)$q$,
    $q$# Her sayıyı kontrol et
nums = [2, 4, 6]
for n in nums:
    print(n * 2)$q$,
    $q$["stores three numbers in a list","loops over each number in the list","multiplies each number by 2 and prints the result"]$q$::jsonb,
    $q$["üç sayıyı bir listede saklar","listede her sayı üzerinde döngü yapar","her sayıyı ikiyle çarpar ve sonucu yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u06-l3-q6$q$,
    $q$python$q$,
    $q$py-u06-l3$q$,
    $q$# Count down until zero
num = 5
while num > 0:
    print(num)
    num = num - 1$q$,
    $q$# Sıfıra kadar geriye say
num = 5
while num > 0:
    print(num)
    num = num - 1$q$,
    $q$["starts with num at 5","uses a while loop with the condition num > 0","decreases num by 1 each time","stops when num reaches 0"]$q$::jsonb,
    $q$["num'u beşle başlatır","num > 0 koşuluyla while döngüsü kullanır","num'u her seferde birle azaltır","num sıfıra ulaşınca durur"]$q$::jsonb
  ),
  (
    $q$py-u06-l4-q6$q$,
    $q$python$q$,
    $q$py-u06-l4$q$,
    $q$# Build a combined message
message = ""
for word in ["Hello", "World"]:
    message = message + word + " "
print(message)$q$,
    $q$# Birleşik bir mesaj oluştur
message = ""
for word in ["Hello", "World"]:
    message = message + word + " "
print(message)$q$,
    $q$["starts with an empty string for the accumulator","loops over two words","adds each word and a space to the message","prints the combined result"]$q$::jsonb,
    $q$["biriktirim için boş bir metinle başlar","iki sözcük üzerinde döngü yapar","her sözcüğü ve bir boşluğu mesaja ekler","birleşen sonucu yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u07-l1-q6$q$,
    $q$python$q$,
    $q$py-u07-l1$q$,
    $q$# A shopping list with three items
shop = ["milk", "bread", "eggs"]
first = shop[0]
last = shop[-1]
print(first + " and " + last)$q$,
    $q$# Üç öğesi olan bir alışveriş listesi
shop = ["milk", "bread", "eggs"]
first = shop[0]
last = shop[-1]
print(first + " and " + last)$q$,
    $q$["creates a list with three items","gets the first item with index 0","gets the last item with index -1","joins and prints the first and last"]$q$::jsonb,
    $q$["üç öğeli bir liste oluşturur","0 dizini ile ilk öğeyi alır","-1 dizini ile son öğeyi alır","ilk ve son öğeyi birleştirir ve yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u07-l2-q6$q$,
    $q$python$q$,
    $q$py-u07-l2$q$,
    $q$# Build a task list
tasks = []
tasks.append("wake up")
tasks.append("eat")
tasks.pop()
tasks.append("sleep")$q$,
    $q$# Bir yapılacaklar listesi oluştur
tasks = []
tasks.append("wake up")
tasks.append("eat")
tasks.pop()
tasks.append("sleep")$q$,
    $q$["starts with an empty list","adds wake up and eat","removes the last item (eat) with pop","adds sleep"]$q$::jsonb,
    $q$["boş bir liste ile başlar","wake up ve eat ekler","pop ile son öğeyi (eat) siler","sleep ekler"]$q$::jsonb
  ),
  (
    $q$py-u07-l3-q6$q$,
    $q$python$q$,
    $q$py-u07-l3$q$,
    $q$# Find average grade
grades = [85, 92, 78, 88]
highest = max(grades)
lowest = min(grades)
print(highest - lowest)$q$,
    $q$# En yüksek ve en düşük notu bul
grades = [85, 92, 78, 88]
highest = max(grades)
lowest = min(grades)
print(highest - lowest)$q$,
    $q$["stores four grades in a list","finds the highest grade with max()","finds the lowest grade with min()","calculates and prints the difference"]$q$::jsonb,
    $q$["dört notu bir listede saklar","max() ile en yüksek notu bulur","min() ile en düşük notu bulur","farkını hesaplar ve yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u07-l4-q6$q$,
    $q$python$q$,
    $q$py-u07-l4$q$,
    $q$# Count votes for each fruit
votes = {"apple": 5, "banana": 3, "cherry": 5}
for fruit in votes:
    print(fruit, votes[fruit])$q$,
    $q$# Her meyve için oyları say
votes = {"apple": 5, "banana": 3, "cherry": 5}
for fruit in votes:
    print(fruit, votes[fruit])$q$,
    $q$["creates a dictionary with three fruits and their vote counts","loops over each key in the dictionary","prints each fruit name and its corresponding vote count"]$q$::jsonb,
    $q$["üç meyve ve oylama sayılarını içeren bir sözlük oluşturur","sözlükteki her anahtar üzerinde döner","her meyvenin adını ve oy sayısını yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u08-l1-q6$q$,
    $q$python$q$,
    $q$py-u08-l1$q$,
    $q$# A function that greets
def wave():
    print("Hello!")

wave()
wave()$q$,
    $q$# Selamlaştıran bir fonksiyon
def wave():
    print("Hello!")

wave()
wave()$q$,
    $q$["defines a function named wave","the function prints Hello!","calls wave twice, so it prints twice"]$q$::jsonb,
    $q$["wave adında bir fonksiyon tanımlar","fonksiyon Hello! yazdırır","wave'i iki kez çağırır, bu nedenle iki kez yazdırılır"]$q$::jsonb
  ),
  (
    $q$py-u08-l2-q6$q$,
    $q$python$q$,
    $q$py-u08-l2$q$,
    $q$# Repeats a word
def repeat_word(word, times):
    for i in range(times):
        print(word)

repeat_word("Hi", 3)$q$,
    $q$# Bir kelimeyi tekrar eder
def repeat_word(word, times):
    for i in range(times):
        print(word)

repeat_word("Hi", 3)$q$,
    $q$["takes two parameters: word and times","loops from 0 to times","prints the word each time through the loop"]$q$::jsonb,
    $q$["iki parametre alır: word ve times","0'dan times'a kadar döngü yapar","her döngüde word'ü yazdırır"]$q$::jsonb
  ),
  (
    $q$py-u08-l3-q6$q$,
    $q$python$q$,
    $q$py-u08-l3$q$,
    $q$# Returns the larger of two numbers
def max_of_two(a, b):
    if a > b:
        return a
    else:
        return b

largest = max_of_two(7, 3)
print(largest)$q$,
    $q$# İki sayıdan büyüğünü döndürür
def max_of_two(a, b):
    if a > b:
        return a
    else:
        return b

largest = max_of_two(7, 3)
print(largest)$q$,
    $q$["defines a function with two parameters","uses an if-else to compare them","returns whichever is larger"]$q$::jsonb,
    $q$["iki parametreli bir fonksiyon tanımlar","if-else ile onları karşılaştırır","hangisi büyük ise onu döndürür"]$q$::jsonb
  ),
  (
    $q$py-u08-l4-q6$q$,
    $q$python$q$,
    $q$py-u08-l4$q$,
    $q$# Adds numbers with a default start
def add_to(num, start=0):
    return start + num

print(add_to(5))
print(add_to(5, 10))$q$,
    $q$# Varsayılan başlangıçla sayıları toplar
def add_to(num, start=0):
    return start + num

print(add_to(5))
print(add_to(5, 10))$q$,
    $q$["has two parameters, one with a default","start defaults to 0 if not provided","returns start + num"]$q$::jsonb,
    $q$["iki parametresi var, biri varsayılan değere sahip","sağlanmazsa start 0 varsayılır","start + num döndürür"]$q$::jsonb
  ),
  (
    $q$js-u01-l1-q6$q$,
    $q$javascript$q$,
    $q$js-u01-l1$q$,
    $q$// Display a greeting
console.log("Welcome to JavaScript");$q$,
    $q$// Bir selamlamayı göster
console.log("Welcome to JavaScript");$q$,
    $q$["calls console.log","prints the text in quotes","outputs to the screen"]$q$::jsonb,
    $q$["console.log'u çağırır","tırnak içindeki metni yazdırır","ekrana çıktı verir"]$q$::jsonb
  ),
  (
    $q$js-u01-l2-q6$q$,
    $q$javascript$q$,
    $q$js-u01-l2$q$,
    $q$// Announce the program
console.log("Starting...");
// Say the number
console.log(10);$q$,
    $q$// Programı duyur
console.log("Starting...");
// Sayıyı söyle
console.log(10);$q$,
    $q$["prints two lines","first line is text","second line is a number"]$q$::jsonb,
    $q$["iki satır yazdırır","birinci satır metindir","ikinci satır bir sayıdır"]$q$::jsonb
  ),
  (
    $q$js-u01-l3-q6$q$,
    $q$javascript$q$,
    $q$js-u01-l3$q$,
    $q$// Double quotes contain the text
console.log("JavaScript is fun");
// Single quotes also work
console.log('It is powerful');$q$,
    $q$// Çift tırnaklar metni içerir
console.log("JavaScript is fun");
// Tek tırnaklar da çalışır
console.log('It is powerful');$q$,
    $q$["double quotes create a string","single quotes also create a string","both quote types work the same way"]$q$::jsonb,
    $q$["çift tırnaklar bir string oluşturur","tek tırnaklar da bir string oluşturur","her iki tırnak türü aynı şekilde çalışır"]$q$::jsonb
  ),
  (
    $q$js-u01-l4-q6$q$,
    $q$javascript$q$,
    $q$js-u01-l4$q$,
    $q$// First output
console.log("A");
// Second output
console.log("B");
// Third output
console.log("C");$q$,
    $q$// İlk çıktı
console.log("A");
// İkinci çıktı
console.log("B");
// Üçüncü çıktı
console.log("C");$q$,
    $q$["runs from top to bottom","prints A first, then B, then C","each console.log creates a new line"]$q$::jsonb,
    $q$["yukarıdan aşağıya çalışır","önce A'yı, sonra B'yi, sonra C'yi yazdırır","her console.log yeni bir satır oluşturur"]$q$::jsonb
  ),
  (
    $q$js-u02-l1-q6$q$,
    $q$javascript$q$,
    $q$js-u02-l1$q$,
    $q$// Declares a starting value that won't change
const principal = 1000;
let balance = principal;
console.log(balance);$q$,
    $q$// Değişmeyecek bir başlangıç değeri bildirir
const principal = 1000;
let balance = principal;
console.log(balance);$q$,
    $q$["const principal stores an unchanging value","let balance starts with the same value","the code prints the current balance"]$q$::jsonb,
    $q$["const principal değişmeyecek bir değer saklar","let balance aynı değerle başlar","kod o anki bakiyeyi yazdırır"]$q$::jsonb
  ),
  (
    $q$js-u02-l2-q6$q$,
    $q$javascript$q$,
    $q$js-u02-l2$q$,
    $q$// Builds a message with a name and an age
const name = "Alice";
const age = 30;
console.log(name + " is " + age + " years old");$q$,
    $q$// Bir isim ve yaş ile mesaj oluşturur
const name = "Alice";
const age = 30;
console.log(name + " is " + age + " years old");$q$,
    $q$["stores the name Alice in a variable","stores the age 30 in a variable","joins them with text to create a sentence"]$q$::jsonb,
    $q$["Alice ismini bir değişkende saklar","30 yaşını bir değişkende saklar","onları metinle birleştirerek cümle oluşturur"]$q$::jsonb
  ),
  (
    $q$js-u02-l3-q6$q$,
    $q$javascript$q$,
    $q$js-u02-l3$q$,
    $q$// Converts the number on purpose before joining
const num = 5;
const text = String(num) + " apples";
console.log(text);$q$,
    $q$// Birleştirmeden önce sayıyı bilerek dönüştürür
const num = 5;
const text = String(num) + " apples";
console.log(text);$q$,
    $q$["stores the number 5 in a variable","converts it to a string using String()","joins it with \" apples\" to create a phrase"]$q$::jsonb,
    $q$["5 sayısını bir değişkende saklar","String() kullanarak string'e dönüştürür","bunu \" apples\" ile birleştirerek bir ifade oluşturur"]$q$::jsonb
  ),
  (
    $q$js-u02-l4-q6$q$,
    $q$javascript$q$,
    $q$js-u02-l4$q$,
    $q$// Intentional empty value
const a = null;
// Unset variable
let b;
console.log(a);
console.log(b);$q$,
    $q$// Kasten boş değer
const a = null;
// Atanmamış değişken
let b;
console.log(a);
console.log(b);$q$,
    $q$["null is assigned on purpose to mean no value","undefined appears when a variable is declared but never assigned","printing them shows null and undefined, two different empty states"]$q$::jsonb,
    $q$["null, değer yok anlamında bilerek atanır","undefined, bir değişken tanımlanıp değer verilmediğinde ortaya çıkar","yazdırıldıklarında null ve undefined, iki farklı boş durumu gösterir"]$q$::jsonb
  ),
  (
    $q$js-u03-l1-q6$q$,
    $q$javascript$q$,
    $q$js-u03-l1$q$,
    $q$// Combine strings two ways
let first = "John";
let last = "Smith";
console.log(first + " " + last);
console.log(`${first} ${last}`);$q$,
    $q$// Metinleri iki şekilde birleştir
let first = "John";
let last = "Smith";
console.log(first + " " + last);
console.log(`${first} ${last}`);$q$,
    $q$["stores two strings in variables","uses + to join them on one line","uses template literals to join them on another line"]$q$::jsonb,
    $q$["iki metni değişkenlerde saklar","bir satırda + ile birleştirir","başka bir satırda template literals ile birleştirir"]$q$::jsonb
  ),
  (
    $q$js-u03-l2-q6$q$,
    $q$javascript$q$,
    $q$js-u03-l2$q$,
    $q$// Get the length and first character
let name = "Emma";
console.log(name.length);
console.log(name[0]);
console.log(name.toLowerCase());$q$,
    $q$// Uzunluğu ve ilk karakteri al
let name = "Emma";
console.log(name.length);
console.log(name[0]);
console.log(name.toLowerCase());$q$,
    $q$["uses .length to get the number of characters","uses [0] to get the first character","uses .toLowerCase() to convert to lowercase"]$q$::jsonb,
    $q$[".length kullanarak karakter sayısını alır","[0] kullanarak ilk karakteri alır",".toLowerCase() kullanarak küçük harfe çevirir"]$q$::jsonb
  ),
  (
    $q$js-u03-l3-q6$q$,
    $q$javascript$q$,
    $q$js-u03-l3$q$,
    $q$// First calculation
console.log(20 - 8 / 4);
// Second calculation
console.log((20 - 8) / 4);$q$,
    $q$// İlk hesaplama
console.log(20 - 8 / 4);
// İkinci hesaplama
console.log((20 - 8) / 4);$q$,
    $q$["first line: division happens before subtraction","second line: parentheses force subtraction first","parentheses change the order of operations"]$q$::jsonb,
    $q$["ilk satır: bölme çıkarmadan önce olur","ikinci satır: parantezler çıkarmayı önce yapmaya zorlar","parantezler işlem sırasını değiştirir"]$q$::jsonb
  ),
  (
    $q$js-u03-l4-q6$q$,
    $q$javascript$q$,
    $q$js-u03-l4$q$,
    $q$// Convert a price to cents and round it
let price = 19.99;
console.log(price * 100);
console.log(Math.round(price * 100));
console.log((price * 100).toFixed(0));$q$,
    $q$// Bir fiyatı sent'e çevirip yuvarla
let price = 19.99;
console.log(price * 100);
console.log(Math.round(price * 100));
console.log((price * 100).toFixed(0));$q$,
    $q$["multiplies 19.99 by 100, which lands on 1998.9999999999998 due to floating-point rounding","uses Math.round to clean the result up to the nearest integer, 1999","uses toFixed(0) to format the same result as the string \"1999\""]$q$::jsonb,
    $q$["19.99'u 100 ile çarpar, kayan nokta yuvarlama hatası yüzünden sonuç 1998.9999999999998 çıkar","Math.round ile sonucu en yakın tam sayı olan 1999'a temizler","toFixed(0) ile aynı sonucu \"1999\" string'i olarak biçimlendirir"]$q$::jsonb
  ),
  (
    $q$js-u04-l1-q6$q$,
    $q$javascript$q$,
    $q$js-u04-l1$q$,
    $q$// Checks if the user is old enough
let age = 16;
if (age >= 13) {
  console.log("Welcome");
} else {
  console.log("Too young");
}$q$,
    $q$// Kullanıcının yeterince yaşlı olup olmadığını kontrol eder
let age = 16;
if (age >= 13) {
  console.log("Welcome");
} else {
  console.log("Too young");
}$q$,
    $q$["compares age to 13","prints Welcome if age is at least 13","prints Too young otherwise"]$q$::jsonb,
    $q$["age'i 13 ile karşılaştırır","age en az 13 ise Welcome yazdırır","aksi takdirde Too young yazdırır"]$q$::jsonb
  ),
  (
    $q$js-u04-l2-q6$q$,
    $q$javascript$q$,
    $q$js-u04-l2$q$,
    $q$// Detects when the password is correct
let password = "secret123";
if (password === "secret123") {
  console.log("Access granted");
} else {
  console.log("Wrong password");
}$q$,
    $q$// Şifre doğru olduğunda algılar
let password = "secret123";
if (password === "secret123") {
  console.log("Access granted");
} else {
  console.log("Wrong password");
}$q$,
    $q$["uses === to compare password exactly","prints Access granted if password matches","prints Wrong password if it does not match"]$q$::jsonb,
    $q$["şifreyi tam olarak karşılaştırmak için === kullanır","password eşleşirse Access granted yazdırır","eşleşmezse Wrong password yazdırır"]$q$::jsonb
  ),
  (
    $q$js-u04-l3-q6$q$,
    $q$javascript$q$,
    $q$js-u04-l3$q$,
    $q$// Determines discount level
let price = 100;
let isMember = true;
if (price > 50 && isMember) {
  console.log("20% off");
} else if (price > 50) {
  console.log("10% off");
} else {
  console.log("No discount");
}$q$,
    $q$// İndirim seviyesini belirler
let price = 100;
let isMember = true;
if (price > 50 && isMember) {
  console.log("20% off");
} else if (price > 50) {
  console.log("10% off");
} else {
  console.log("No discount");
}$q$,
    $q$["checks if price is over 50 AND isMember is true","gives 20% off if both conditions are true","gives 10% off if only price is over 50","gives no discount otherwise"]$q$::jsonb,
    $q$["price 50'den büyükse VE isMember doğruysa kontrol eder","her iki koşul da doğruysa %20 indirim verir","sadece price 50'den büyükse %10 indirim verir","aksi takdirde indirim vermez"]$q$::jsonb
  ),
  (
    $q$js-u04-l4-q6$q$,
    $q$javascript$q$,
    $q$js-u04-l4$q$,
    $q$// Suggests an action based on inventory
let inventory = 5;
let message = inventory > 0 ? "In stock" : "Out of stock";
if (message) {
  console.log(message);
}$q$,
    $q$// Envantere dayalı olarak bir eylem önerir
let inventory = 5;
let message = inventory > 0 ? "In stock" : "Out of stock";
if (message) {
  console.log(message);
}$q$,
    $q$["uses ternary to pick In stock or Out of stock","assigns the result to message","uses if with truthiness to print if message is not empty","any non-empty string is truthy"]$q$::jsonb,
    $q$["In stock veya Out of stock'u seçmek için ternary kullanır","sonucu message'a atar","message boş değilse yazdırmak için if ile truthiness kullanır","boş olmayan herhangi bir metin truthy'dir"]$q$::jsonb
  ),
  (
    $q$js-u05-l1-q6$q$,
    $q$javascript$q$,
    $q$js-u05-l1$q$,
    $q$// Store three measurements and print the first
let temps = [72, 68, 75];
console.log(temps[0]);$q$,
    $q$// Üç ölçümü depola ve ilkini yazdır
let temps = [72, 68, 75];
console.log(temps[0]);$q$,
    $q$["creates an array of three temperature values","accesses the element at index 0","prints that value"]$q$::jsonb,
    $q$["üç sıcaklık değerinden oluşan dizi oluşturur","indeks 0'daki öğeye erişir","o değeri yazdırır"]$q$::jsonb
  ),
  (
    $q$js-u05-l2-q6$q$,
    $q$javascript$q$,
    $q$js-u05-l2$q$,
    $q$// Build a list of purchases
let cart = [];
cart.push("milk");
cart.push("bread");
console.log(cart.length);$q$,
    $q$// Alışveriş listesi oluştur
let cart = [];
cart.push("milk");
cart.push("bread");
console.log(cart.length);$q$,
    $q$["creates an empty array","adds two items with push()","prints the count of items"]$q$::jsonb,
    $q$["boş dizi oluşturur","push() ile iki öğe ekler","öğelerin sayısını yazdırır"]$q$::jsonb
  ),
  (
    $q$js-u05-l3-q6$q$,
    $q$javascript$q$,
    $q$js-u05-l3$q$,
    $q$// Process every score in the array
let scores = [85, 92, 78];
for (let score of scores) {
  if (score >= 90) {
    console.log("High");
  }
}$q$,
    $q$// Dizideki her puanı işle
let scores = [85, 92, 78];
for (let score of scores) {
  if (score >= 90) {
    console.log("High");
  }
}$q$,
    $q$["loops through each score in the array","checks if the score is 90 or higher","prints High only for scores that meet the condition"]$q$::jsonb,
    $q$["dizideki her puanı döngü ile geçer","puanın 90 veya daha yüksek olup olmadığını kontrol eder","sadece koşulu karşılayan puanlar için High yazdırır"]$q$::jsonb
  ),
  (
    $q$js-u05-l4-q6$q$,
    $q$javascript$q$,
    $q$js-u05-l4$q$,
    $q$// Find all scores that need improvement
let scores = [85, 92, 78, 88, 95];
let needsWork = scores.filter(s => s < 85);
console.log(needsWork);$q$,
    $q$// İyileştirmeye ihtiyaç duyan puanları bul
let scores = [85, 92, 78, 88, 95];
let needsWork = scores.filter(s => s < 85);
console.log(needsWork);$q$,
    $q$["starts with an array of scores","uses filter to keep only scores below 85","stores the result in a new array called needsWork"]$q$::jsonb,
    $q$["puanlar dizisinden başlar","85'ten az puanları tutmak için filter kullanır","sonucu needsWork adlı yeni dizide saklar"]$q$::jsonb
  ),
  (
    $q$js-u06-l1-q6$q$,
    $q$javascript$q$,
    $q$js-u06-l1$q$,
    $q$// Announces the start of the game
function startGame() {
  console.log("Game started!");
}

startGame();$q$,
    $q$// Oyunun başlangıcını duyurur
function startGame() {
  console.log("Game started!");
}

startGame();$q$,
    $q$["defines a function named startGame","the function has code inside that prints a message","calls the function to run the code"]$q$::jsonb,
    $q$["startGame adında bir fonksiyon tanımlar","fonksiyonun içinde bir mesaj yazdıran kod vardır","kodu çalıştırmak için fonksiyonu çağırır"]$q$::jsonb
  ),
  (
    $q$js-u06-l2-q6$q$,
    $q$javascript$q$,
    $q$js-u06-l2$q$,
    $q$// Calculates the price after tax
function withTax(price) {
  return price * 1.2;
}

const total = withTax(100);
console.log(total);$q$,
    $q$// Vergi sonrası fiyatı hesaplar
function withTax(price) {
  return price * 1.2;
}

const total = withTax(100);
console.log(total);$q$,
    $q$["defines a function withTax that multiplies the input by 1.2","calls the function with 100","stores the result (120) in total and prints it"]$q$::jsonb,
    $q$["girdileri 1.2 ile çarpan withTax fonksiyonunu tanımlar","fonksiyonu 100 ile çağırır","sonucu (120) total'de saklar ve yazdırır"]$q$::jsonb
  ),
  (
    $q$js-u06-l3-q6$q$,
    $q$javascript$q$,
    $q$js-u06-l3$q$,
    $q$// Regular function
function add(a, b) {
  return a + b;
}

// Arrow function
const add2 = (a, b) => {
  return a + b;
};$q$,
    $q$// Düzenli fonksiyon
function add(a, b) {
  return a + b;
}

// Arrow fonksiyon
const add2 = (a, b) => {
  return a + b;
};$q$,
    $q$["function keyword vs const and arrow syntax","regular function is declared, arrow is assigned to a variable","both do the same thing and return the same result"]$q$::jsonb,
    $q$["function anahtar sözcüğü vs const ve arrow söz dizimi","düzenli fonksiyon bildirilir, arrow bir değişkene atanır","her ikisi de aynı şeyi yapar ve aynı sonucu döndürür"]$q$::jsonb
  ),
  (
    $q$js-u06-l4-q6$q$,
    $q$javascript$q$,
    $q$js-u06-l4$q$,
    $q$// x lives in global scope
const x = 5;

function test() {
  // y lives in function scope
  const y = 10;
  console.log(x + y);
}

test();
console.log(x);$q$,
    $q$// x genel kapsamda yaşar
const x = 5;

function test() {
  // y fonksiyon kapsamında yaşar
  const y = 10;
  console.log(x + y);
}

test();
console.log(x);$q$,
    $q$["x is global and can be used anywhere","y is local to the function and only exists inside","inside the function both x and y can be used; outside only x is visible"]$q$::jsonb,
    $q$["x genel ve her yerde kullanılabilir","y fonksiyona yereldir ve sadece içinde vardır","fonksiyon içinde her ikisi de kullanılabilir; dışında sadece x görünür"]$q$::jsonb
  )
on conflict (question_id) do update set
  course_id = excluded.course_id,
  lesson_id = excluded.lesson_id,
  code_en = excluded.code_en,
  code_tr = excluded.code_tr,
  key_points_en = excluded.key_points_en,
  key_points_tr = excluded.key_points_tr,
  updated_at = now();

-- Rubrics for questions that no longer exist in the bundle are dropped so a
-- stale id cannot be graded.
delete from public.question_rubrics
where question_id not in (
  $q$py-u01-l1-q6$q$,
  $q$py-u01-l2-q6$q$,
  $q$py-u01-l3-q6$q$,
  $q$py-u01-l4-q6$q$,
  $q$py-u02-l1-q6$q$,
  $q$py-u02-l2-q6$q$,
  $q$py-u02-l3-q6$q$,
  $q$py-u02-l4-q6$q$,
  $q$py-u03-l1-q6$q$,
  $q$py-u03-l2-q6$q$,
  $q$py-u03-l3-q6$q$,
  $q$py-u03-l4-q6$q$,
  $q$py-u04-l1-q6$q$,
  $q$py-u04-l2-q6$q$,
  $q$py-u04-l3-q6$q$,
  $q$py-u04-l4-q6$q$,
  $q$py-u05-l1-q6$q$,
  $q$py-u05-l2-q6$q$,
  $q$py-u05-l3-q6$q$,
  $q$py-u05-l4-q6$q$,
  $q$py-u06-l1-q6$q$,
  $q$py-u06-l2-q6$q$,
  $q$py-u06-l3-q6$q$,
  $q$py-u06-l4-q6$q$,
  $q$py-u07-l1-q6$q$,
  $q$py-u07-l2-q6$q$,
  $q$py-u07-l3-q6$q$,
  $q$py-u07-l4-q6$q$,
  $q$py-u08-l1-q6$q$,
  $q$py-u08-l2-q6$q$,
  $q$py-u08-l3-q6$q$,
  $q$py-u08-l4-q6$q$,
  $q$js-u01-l1-q6$q$,
  $q$js-u01-l2-q6$q$,
  $q$js-u01-l3-q6$q$,
  $q$js-u01-l4-q6$q$,
  $q$js-u02-l1-q6$q$,
  $q$js-u02-l2-q6$q$,
  $q$js-u02-l3-q6$q$,
  $q$js-u02-l4-q6$q$,
  $q$js-u03-l1-q6$q$,
  $q$js-u03-l2-q6$q$,
  $q$js-u03-l3-q6$q$,
  $q$js-u03-l4-q6$q$,
  $q$js-u04-l1-q6$q$,
  $q$js-u04-l2-q6$q$,
  $q$js-u04-l3-q6$q$,
  $q$js-u04-l4-q6$q$,
  $q$js-u05-l1-q6$q$,
  $q$js-u05-l2-q6$q$,
  $q$js-u05-l3-q6$q$,
  $q$js-u05-l4-q6$q$,
  $q$js-u06-l1-q6$q$,
  $q$js-u06-l2-q6$q$,
  $q$js-u06-l3-q6$q$,
  $q$js-u06-l4-q6$q$
);
